# TODO 替换为自己的包名
name: flutter_project_template
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: 3.22.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  provider: ^6.1.2
  shared_preferences: ^2.3.2
  fluttertoast: ^8.2.8
  dio: ^5.7.0
  page_transition: ^2.1.0
  swipeable_page_route: ^0.4.4
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  test: ^1.25.7
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
